alog -O2 -protect 0 -msg 5 -sve "$dsn/src/pixelcircuittb.sv"
alog -O2 -protect 0 -msg 5 -sve "$dsn/src/re_control.sv"
alog -O2 -protect 0 -msg 5 -sve "$dsn/src/fsm_control.sv"
alog -O2 -protect 0 -msg 5 -sve "$dsn/src/ctrl_exp_time.sv"
alog -O2 -protect 0 -msg 5 -sve "$dsn/src/timer_counter.sv"
